repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17  # Use the latest version available
  hooks:
  - id: mdformat
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.7
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
